slides: images
	pdflatex betterxml-talk
	pdflatex betterxml-talk

images:
	dot -Tpdf expression_tree.dot > expression_tree.pdf

clean:
	-rm *.pdf
	-rm *.aux
	-rm *.log
	-rm *.nav
	-rm *.snm
	-rm *.toc
	-rm *.out
